#!/bin/bash
echo "========================================"
echo "    External Access Helper (Linux/Mac)"
echo "========================================"
echo ""
echo "Your IP Addresses:"
hostname -I 2>/dev/null || ifconfig 2>/dev/null | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
echo ""
echo "----------------------------------------"
echo "FACULTY PORTAL (Management)"
echo "----------------------------------------"
echo "URL: http://[YOUR_IP]:9876"
echo ""
echo "----------------------------------------"
echo "STUDENT PORTAL (Quiz)"
echo "----------------------------------------"
echo "URL: http://[YOUR_IP]:8080"
echo ""
echo "----------------------------------------"
echo "INSTRUCTIONS:"
echo "1. Connect devices to the same network."
echo "2. Open browser on any device."
echo "3. Replace [YOUR_IP] with the IP shown above."
echo "========================================"
