package com.quiz.model;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * Records the student's submitted code, the assigned problem context,
 * and the grading/authorship verification details computed by Google Gemini.
 */
@Entity
public class CodingSubmission {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Long sessionId;
    private Long studentId;

    @Lob
    @Column(length = 50000)
    private String code;

    private String programmingLanguage;
    private String assignedProblem; // e.g., "Problem A (Even)" or "Problem B (Odd)"
    private Integer score; // Marks from 0 to 100

    @Lob
    @Column(length = 10000)
    private String aiFeedback; // Correction and suggestions by Gemini

    private Double aiGeneratedProbability; // Estimation that code was generated by LLM (0-100%)

    @Lob
    @Column(length = 10000)
    private String aiDetectionExplanation; // Explanation by Gemini on AI detection check

    private Instant submittedAt = Instant.now();
    private boolean cheated; // Disqualified if focus is lost

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSessionId() {
        return sessionId;
    }

    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    public Long getStudentId() {
        return studentId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getProgrammingLanguage() {
        return programmingLanguage;
    }

    public void setProgrammingLanguage(String programmingLanguage) {
        this.programmingLanguage = programmingLanguage;
    }

    public String getAssignedProblem() {
        return assignedProblem;
    }

    public void setAssignedProblem(String assignedProblem) {
        this.assignedProblem = assignedProblem;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public String getAiFeedback() {
        return aiFeedback;
    }

    public void setAiFeedback(String aiFeedback) {
        this.aiFeedback = aiFeedback;
    }

    public Double getAiGeneratedProbability() {
        return aiGeneratedProbability;
    }

    public void setAiGeneratedProbability(Double aiGeneratedProbability) {
        this.aiGeneratedProbability = aiGeneratedProbability;
    }

    public String getAiDetectionExplanation() {
        return aiDetectionExplanation;
    }

    public void setAiDetectionExplanation(String aiDetectionExplanation) {
        this.aiDetectionExplanation = aiDetectionExplanation;
    }

    public Instant getSubmittedAt() {
        return submittedAt;
    }

    public void setSubmittedAt(Instant submittedAt) {
        this.submittedAt = submittedAt;
    }

    public boolean isCheated() {
        return cheated;
    }

    public void setCheated(boolean cheated) {
        this.cheated = cheated;
    }
}
